org.apache.openjpa.persistence.ArgumentException: "com.haulmont.cuba.security.entity.ScreenHistoryEntity.entityId" decla res column "ENTITY_ID", but this column does not exist in table "PUBLIC.SEC_SCREEN_HISTORY".